version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: airless-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_ruby168
      MONGO_INITDB_ROOT_PASSWORD: 258369ss
      MONGO_INITDB_DATABASE: airless-db
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
